import { randomUUID } from 'node:crypto'
import { escapeLatex } from './LabLatex.mjs'
import { createTable } from './LabTableModel.mjs'
export const CLEANER_PROFILE = 'cleaner-production-01'
export const REFERENCE_DOCX = 'lab-reference.docx'
export function createCleanerManifest() {
  const modules = []
  const add = (title, kind = 'section', parentId = null) => {
    const id = randomUUID()
    modules.push({
      id,
      title,
      kind,
      parentId,
      hidden: false,
      ...(kind === 'table' && { table: createTable() }),
    })
    return id
  }
  add('Abstract', 'abstract')
  add('Keywords', 'unnumbered')
  add('Introduction')
  const experiments = add('Experiments')
  add('Materials', 'section', experiments)
  add('CO2 solubility measurement', 'section', experiments)
  const model = add('Mathematical model')
  const thermo = add('Thermodynamic model', 'section', model)
  add('Chemical and phase equilibrium equations', 'section', thermo)
  add('Activity coefficient model', 'section', thermo)
  add('Heat of absorption', 'section', thermo)
  add('Model coefficients', 'table', model)
  add('ANN model', 'section', model)
  add('Error functions and evaluation methods', 'section', model)
  add('Shortcut method', 'section', model)
  const results = add('Results and discussion')
  add('CO2 solubility', 'section', results)
  add('Absorption behaviors', 'section', results)
  add('Performance of absorbents', 'section', results)
  add('Prediction models', 'section', results)
  add('Conclusions')
  add('Acknowledgements', 'unnumbered')
  add('Declaration of competing interests', 'unnumbered')
  add('Data availability', 'unnumbered')
  add('References', 'unnumbered')
  add('Highlights', 'highlights')
  return {
    format: 'overleaf-lab-assembly',
    schemaVersion: 1,
    version: 1,
    profile: CLEANER_PROFILE,
    title: 'Manuscript title\nA concise subtitle for the study',
    metadata: {
      authors: 'First Author[a], Second Author[b,*]',
      affiliations:
        'Department and institution, city, country\nSecond department and institution, city, country',
      authorNotes: 'Corresponding author: name and email',
    },
    modules,
  }
}
export function initialCleanerBody(module) {
  if (module.kind === 'table') return ''
  if (module.kind === 'highlights')
    return '\\begin{itemize}\n\\item Write the first highlight here.\n\\item Write the second highlight here.\n\\item Write the third highlight here.\n\\end{itemize}\n'
  if (module.title === 'Keywords')
    return 'Keyword one; Keyword two; Keyword three.\n'
  return `Write the ${module.title.toLowerCase()} here.\n`
}
export function superscripts(text) {
  return text
    .split(/(\[[a-zA-Z0-9,*]+\])/)
    .map(part =>
      part.startsWith('[') && part.endsWith(']')
        ? `\\textsuperscript{${escapeLatex(part.slice(1, -1))}}`
        : escapeLatex(part),
    )
    .join('')
}
export function cleanerPreamble(manifest) {
  const meta = manifest.metadata || {
    authors: '',
    affiliations: '',
    authorNotes: '',
  }
  return [
    '% Generated by the lab assembly editor. Edit content in the module files.',
    '\\documentclass[12pt,a4paper]{article}',
    '\\usepackage{fontspec}',
    '\\IfFileExists{/usr/local/share/fonts/lab/Times New Roman.ttf}{\\setmainfont{Times New Roman.ttf}[Path=/usr/local/share/fonts/lab/,BoldFont=Times New Roman Bold.ttf,ItalicFont=Times New Roman Italic.ttf,BoldItalicFont=Times New Roman Bold Italic.ttf]}{\\setmainfont{TeX Gyre Termes}}',
    '\\usepackage{unicode-math}',
    '\\setmathfont{TeX Gyre Termes Math}',
    '\\usepackage[a4paper,top=30mm,bottom=25.4mm,left=25.4mm,right=25.4mm]{geometry}',
    '\\usepackage{graphicx,amsmath,setspace,indentfirst,titlesec,lineno,natbib}',
    '\\usepackage{array,booktabs,longtable,multirow,caption}',
    '\\captionsetup{font=normalsize,labelfont=bf,textfont=bf,labelsep=period,justification=raggedright,singlelinecheck=false}',
    '\\setlength{\\parindent}{12pt}',
    '\\setlength{\\parskip}{0pt}',
    '\\setlength{\\LTcapwidth}{\\linewidth}',
    '\\setlength{\\LTleft}{0pt}',
    '\\setlength{\\LTright}{0pt}',
    '\\titleformat{\\section}{\\normalfont\\bfseries\\normalsize}{\\thesection.}{0.25em}{}',
    '\\titleformat{\\subsection}{\\normalfont\\bfseries\\normalsize}{\\thesubsection.}{0.25em}{}',
    '\\titleformat{\\subsubsection}{\\normalfont\\bfseries\\normalsize}{\\thesubsubsection.}{0.25em}{}',
    ...['section', 'subsection', 'subsubsection'].map(
      level => `\\titlespacing{\\${level}}{0pt}{27.6pt}{0pt}`,
    ),
    '\\renewcommand{\\linenumberfont}{\\normalfont\\normalsize}',
    '\\setlength{\\linenumbersep}{12pt}',
    '\\begin{document}',
    '\\pagestyle{empty}',
    '\\fontsize{12}{27.6}\\selectfont',
    '\\linenumbers',
    '\\begin{center}',
    '\\fontsize{14}{40.2}\\selectfont\\bfseries',
    manifest.title.split('\n').map(escapeLatex).join('\\\\\n') + '\\par',
    '\\normalfont\\fontsize{12}{27.6}\\selectfont',
    superscripts(meta.authors),
    '\\end{center}',
    ...meta.affiliations
      .split('\n')
      .filter(Boolean)
      .map(
        (line, i) =>
          `\\textsuperscript{${String.fromCharCode(97 + i)}} ${escapeLatex(line)}\\par`,
      ),
    ...(meta.authorNotes
      ? [
          '\\par\\vspace{27.6pt}',
          ...meta.authorNotes
            .split('\n')
            .map(line => `${superscripts(line)}\\par`),
        ]
      : []),
  ]
}
